Update examples.rst
non-admin users get permission denied
jira.exceptions.JIRAError: JiraError HTTP 403 url: https://jira.svale.netledger.com/jira/rest/api/2/issue/365935?notifyUsers=false
	text: To discard the user notification either admin or project admin permissions are required.